 <?php
	$OP_ADD = "ADD";
	$OP_REMOVE = "REMOVE";
	$OP_GETBYID = "GET_BY_ID";
	$OP_GETALL = "GET_ALL";
	$OP_GETBYCAMERA = "GET_BY_CAMERA";
	$OP_ADDFORCAMERA = "ADD_FOR_CAMERA";
	$OP_ADDUSERPERMISSION = "ADD_USER_PERMISSION";
	$OP_GETBYUSER = "GET_BY_USER";
	$OP_GETBYLOCAL = "GET_BY_LOCAL";
	$OP_GETUSERSPERMISSION = "GET_USERS_PERMISSION";
	$OP_CHANGEUSERSPERMISSION = "CHANGE_USERS_PERMISSION";
?>
